FROM ghcr.io/dockhippie/caddy:latest-arm@sha256:8e737ac9879ca6faf3b0f922e4b5485d2ad972e5c639cdc464b740455f215bec

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add php8@testing php8-fpm@testing php8-ctype@testing php8-curl@testing php8-dom@testing php8-gd@testing php8-iconv@testing php8-intl@testing php8-mysqli@testing php8-mysqlnd@testing php8-openssl@testing php8-opcache@testing php8-pdo@testing php8-pdo_mysql@testing php8-pdo_pgsql@testing php8-pdo_sqlite@testing php8-pear@testing php8-pgsql@testing php8-phar@testing php8-sqlite3@testing php8-xml@testing php8-zip@testing php8-mbstring@testing php8-simplexml@testing php8-tokenizer@testing php8-xmlwriter@testing php8-fileinfo@testing php8-soap@testing php8-pecl-apcu@testing php8-pecl-redis@testing php8-pecl-memcached@testing git && \
  ln -sf /usr/bin/php8 /usr/bin/php && \
  rm -rf /var/cache/apk/* /etc/php8/* && \
  mv /srv/www/index.html /srv/www/index.php

VOLUME ["/etc/php8/custom.d"]
EXPOSE 8080

COPY ./overlay /

RUN curl -sSLo - https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && \
  curl -sSLo /etc/php8/browscap.ini http://browscap.org/stream\?q=PHP_BrowsCapINI
