---
name: readme

"on":
  push:
    branches:
      - master
    paths:
      - README.md
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Push readme
        uses: actionhippie/pushrm@v1
        if: github.event_name != 'pull_request'
        with:
          provider: dockerhub
          target: webhippie/php-caddy
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          description: Docker image for php-caddy
          readme: README.md

      - name: Push readme
        uses: actionhippie/pushrm@v1
        with:
          provider: quay
          target: quay.io/webhippie/php-caddy
          apikey: ${{ secrets.QUAY_APIKEY }}
          readme: README.md

...
